name: Lint

on:
  push:
    branches:
      - '**'

jobs:
  run-linters:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Use Node.js version 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint
